package:
  name: termstyle
  version: "0.1.11"

source:
  fn: termstyle-0.1.11.tar.gz
  url: https://pypi.python.org/packages/65/53/4dfdfe12b499f375cc78caca9cf146c01e752bab7713de4510d35e3da306/termstyle-0.1.11.tar.gz
  md5: b6ec81a1c7ebe06f139ce3c294bd3ff8

build:
  # noarch_python: True
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

about:
  home: http://github.com/gfxmonk/termstyle
  license: BSD License
  summary: 'console colouring for python'
  license_family: BSD
