package:
  name: sratoolkit
  version: 2.8.1
source:
  fn: sratoolkit.2.8.1-centos_linux64.tar.gz  # [linux]
  fn: sratoolkit.2.8.1-mac64.tar.gz # [osx]
  url: http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.8.1/sratoolkit.2.8.1-centos_linux64.tar.gz # [linux]
  url: http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.8.1/sratoolkit.2.8.1-mac64.tar.gz # [osx]
  md5: 59047012f84c33ba9ac33ba3ca750bbd # [linux]
  md5: 28a7259881278d7df7eb032c6d42abcc # [osx]

requirements:
  build:
  run:
test:
  commands:
    - 'fastq-dump 2> /dev/null || [[ "$?" == 1 ]]'
    - 'sam-dump 2> /dev/null || [[ "$?" == 3 ]]'
about:
  home: http://ncbi.github.io/sra-tools/
  license: Public Domain
  summary: "The SRA Toolkit and SDK from NCBI is a collection of tools and libraries for using data in the INSDC Sequence Read Archives."
