package:
  name: nikola
  version: "7.8.10"

source:
  fn: Nikola-7.8.10.tar.gz
  url: https://pypi.python.org/packages/f0/c0/693055fe780efa8e7b4096e1a19c5a44935a87b105f0c93df011d339b1b8/Nikola-7.8.10.tar.gz
  md5: a3a4e7f5417f6ce19b6edbbe8b778131
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nikola = nikola:main
    #
    # Would create an entry point called nikola that calls nikola.main()

    - nikola = nikola.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pygments >=1.6
    - pillow >=2.4.0
    - python-dateutil >=2.4.0
    - docutils >=0.12
    - mako >=1.0.0
    - markdown >=2.4.0
    - unidecode >=0.04.16
    - lxml >=3.3.5
    - yapsy >=1.11.223
    - pyrss2gen >=1.1
    - logbook >=0.7.0
    - blinker >=1.3
    - setuptools >=20.3
    - natsort >=3.5.2
    - requests >=2.2.0
    - piexif >=1.0.3
    - doit >=0.30.1

  run:
    - python
    - pygments >=1.6
    - pillow >=2.4.0
    - python-dateutil >=2.4.0
    - docutils >=0.12
    - mako >=1.0.0
    - markdown >=2.4.0
    - unidecode >=0.04.16
    - lxml >=3.3.5
    - yapsy >=1.11.223
    - pyrss2gen >=1.1
    - logbook >=0.7.0
    - blinker >=1.3
    - setuptools >=20.3
    - natsort >=3.5.2
    - requests >=2.2.0
    - piexif >=1.0.3
    - doit >=0.30.1

test:
  # Python imports
  imports:
    - nikola
    - nikola.packages
    - nikola.packages.datecond
    - nikola.packages.tzlocal
    - nikola.plugins
    - nikola.plugins.command
    - nikola.plugins.command.auto
    - nikola.plugins.command.rst2html
    - nikola.plugins.compile
    - nikola.plugins.compile.markdown
    - nikola.plugins.compile.rest
    - nikola.plugins.misc
    - nikola.plugins.task
    - nikola.plugins.task.sitemap
    - nikola.plugins.template

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - nikola --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://getnikola.com/
  license: MIT License
  summary: 'A modular, fast, simple, static website and blog generator'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
