package:
    name: jupyter-vim-binding
    version: v2.0.4
source:
    git_rev: v2.0.4
    git_url: https://github.com/lambdalisue/jupyter-vim-binding
build:
    number: '0'
    skip: 'False'
requirements:
    run:
        - jupyter
        - notebook
        - jupyter_contrib_nbextensions
test: {}
about:
    home: https://github.com/lambdalisue/jupyter-vim-binding
    license: MIT
