package:
    name: mongodb
    version: 3.4.1
source:
    fn: mongodb-linux-x86_64-amazon-3.4.1.tgz
    md5sum: 8f5ce8185e14ff54bde0984305e1833c
    url: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-amazon-3.4.1.tgz
build: {}
requirements:
    run:
        - openssl
test:
    commands:
        - mongod --help
        - mongo --help
about:
    home: https://www.mongodb.com/
    license: GNU AGPL
    summary: A popular NoSQL database system.
