package:
    name: mongodb
    version: 3.4.9
source:
    fn: mongodb-linux-x86_64-rhel62-3.4.9.tgz
    md5sum: c26630a07b46cfb1051bedf7f7362f0c
    url: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel62-3.4.9.tgz
build: {}
requirements:
    run:
        - openssl
test:
    commands:
        - mongod --help
        - mongo --help
about:
    home: https://www.mongodb.com/
    license: GNU AGPL
    summary: A popular NoSQL database system.
