package:
  name: doit
  version: "0.30.3"

source:
  fn: doit-0.30.3.tar.gz
  url: https://pypi.python.org/packages/bf/8a/9941b2fe2d0c8c22fe619281b38d132250d65f7a4a6a54463f7fedf62657/doit-0.30.3.tar.gz
  md5: 8e574838ca72f7174f24c17d2c65639c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - doit = doit:main
    #
    # Would create an entry point called doit that calls doit.main()

    - doit = doit.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cloudpickle
    - macfsevents   # [osx]
    - pyinotify     # [linux]

  run:
    - python
    - cloudpickle
    - macfsevents   # [osx]
    - pyinotify     # [linux]

test:
  # Python imports
  imports:
    - doit

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - doit --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pydoit.org
  license: MIT License
  summary: 'doit - Automation Tool'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
